## Simpler Returns - Part I

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Download the data for Microsoft (‘MSFT’) from Yahoo Finance for the period ‘2000-1-1’ until today.

In [1]:
import numpy as np
import pandas as pd
#from pandas_datareader import data as wb

In [6]:
MSFT = pd.read_csv("D:/Jupyter/fintech/样本数据/MSFT_2000_2017.csv", index_col = 'Date')

In [28]:
MSFT1 = pd.read_excel("D:/Jupyter/fintech/样本数据/MSFT_2000_2017.xls", index_col = 'Date')

In [27]:
MSFT2 = pd.read_excel("D:/Jupyter/fintech/样本数据/MSFT_2000_2017.xlsx", index_col = 'Date')

In [7]:
MSFT.head()

                Open     High      Low     Close  Adj Close    Volume
Date
1999-12-31  58.75000  58.8750  58.1250  58.37500  38.771053  12517600
2000-01-03  58.68750  59.3125  56.0000  58.28125  38.708794  53228400
2000-01-04  56.78125  58.5625  56.1250  56.31250  37.401215  54119000
2000-01-05  55.56250  58.1875  54.6875  56.90625  37.795563  64059600
2000-01-06  56.09375  56.9375  54.1875  55.00000  36.529484  54976600

Apply the .**head()** and **.tail()** methods to check if the data is ok. Always pay attention to the dates. Try to get an idea about how the stock price changed during the period.

In [8]:
MSFT.head()

                Open     High      Low     Close  Adj Close    Volume
Date
1999-12-31  58.75000  58.8750  58.1250  58.37500  38.771053  12517600
2000-01-03  58.68750  59.3125  56.0000  58.28125  38.708794  53228400
2000-01-04  56.78125  58.5625  56.1250  56.31250  37.401215  54119000
2000-01-05  55.56250  58.1875  54.6875  56.90625  37.795563  64059600
2000-01-06  56.09375  56.9375  54.1875  55.00000  36.529484  54976600

In [9]:
MSFT.tail()

                 Open       High        Low      Close  Adj Close    Volume
Date
2017-12-06  81.550003  83.139999  81.430000  82.779999  82.779999  26162100
2017-12-07  82.540001  82.800003  82.000000  82.489998  82.489998  23184500
2017-12-08  83.629997  84.580002  83.330002  84.160004  84.160004  24489100
2017-12-11  84.290001  85.370003  84.120003  85.230003  85.230003  20121700
2017-12-12  85.309998  86.050003  85.080002  85.529999  85.529999   7805031

### Simple Rate of Return

Calculate the simple returns of ‘MSFT’ for the given timeframe.

$$
\frac{P_1 - P_0}{P_0} = \frac{P_1}{P_0} - 1
$$

In [10]:
MSFT['simple_return'] = (MSFT['Adj Close'] / MSFT['Adj Close'].shift(1)) - 1
print (MSFT['simple_return'])

Date
1999-12-31         NaN
2000-01-03   -0.001606
2000-01-04   -0.033780
2000-01-05    0.010544
2000-01-06   -0.033498
                ...
2017-12-06    0.014585
2017-12-07   -0.003503
2017-12-08    0.020245
2017-12-11    0.012714
2017-12-12    0.003520
Name: simple_return, Length: 4517, dtype: float64