根据 https://mp.weixin.qq.com/s/EZpWPcUvpi8xIC0KXwTQXQ  ，补充完全部内容， 要求：学号+姓名+HW2 命名。

## 数据模拟

Python 字典，用于模拟生成带有各种问题（缺失值、异常值、重复数据、格式混乱的日期等）的数据。

In [11]:
import pandas as pd
import numpy as np

# 模拟生成数据
data = {
    "姓名": ["张三", "李四", "王五", "赵六", "小明", "小红", "老王", "张三", "赵六"],
    "年龄": [25, 30, 22, np.nan, 29, 26, 28, 25, 200],  # 缺失值 & 异常值
    "工龄": [2, 5, 1, 8, np.nan, 3, -1, 2, 10],        # 缺失值 & 错误数据（负数）
    "薪资": [8000, 12000, 6000, 15000, 10000, 9000, 8500, 8000, 16000],  # 重复行
    "入职日期": ["2022-06-01", "2020/05/15", "2021-09-10", "2019-12-01", 
                 "2023/01/01", "2021-08-15", "2018-03-10", "2022-06-01", "2019-12-01"],  # 日期格式混乱
    "部门": ["市场部", "技术部", "市场部", "技术部", "市场部", "人事部", "技术部", "市场部", "财务部"]
}

df = pd.DataFrame(data)
print("原始数据：\n", df)

# 1. 删除重复行
df = df.drop_duplicates()
print("\n删除重复行后的数据：\n", df)

# 2. 处理缺失值
# 填充年龄和工龄的缺失值为中位数
df['年龄'].fillna(df['年龄'].median(), inplace=True)
df['工龄'].fillna(df['工龄'].median(), inplace=True)
print("\n处理缺失值后的数据：\n", df)

# 3. 处理异常值
# 替换年龄中的异常值（如200）为中位数
df.loc[df['年龄'] > 100, '年龄'] = df['年龄'].median()
# 替换工龄中的负数为0
df.loc[df['工龄'] < 0, '工龄'] = 0
print("\n处理异常值后的数据：\n", df)

# 4. 统一日期格式
df['入职日期'] = pd.to_datetime(df['入职日期'], format='%Y-%m-%d', errors='coerce')
print("\n统一日期格式后的数据：\n", df)

# 5. 检查数据类型
print("\n数据类型：\n", df.dtypes)

原始数据：
    姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
7  张三   25.0   2.0   8000  2022-06-01  市场部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

删除重复行后的数据：
    姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

处理缺失值后的数据：
    姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六   28.0   8.0  15000  2019-12-01  技术部
4  小明   29.0   3.0  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

处理异常值后的数据：
    姓名    年龄    工龄     薪资        入职日期   部门
0  张三  25.0   2.0   8000  2022-06-01  市场部
1  李四  30.0   5.0  12000  2020/05/15  技术部
2  王五  22.0   1.0   6000  2021-09-10  市场部
3  赵六  28.0   8.0  15000  2019-12-01  技术部
4  小明  29.0   3.0  10000  2023/01/01  市场部
5  小红  26.0   3.0   9000  2021-08-15  人事部
6  老王  28.0   0.0   8500  2018-03-10  技术部
8  赵六  28.0  10.0  16000  2019-12-01  财务部

统一日期格式后的数据：
    姓名    年龄    工龄     薪资       入职日期   部门
0  张三  25.0   2.0   8000 2022-06-01  市场部
1  李四  30.0   5.0  12000        NaT  技术部
2  王五  22.0   1.0   6000 2021-09-10  市场部
3  赵六  28.0   8.0  15000 2019-12-01  技术部
4  小明  29.0   3.0  10000        NaT  市场部
5  小红  26.0   3.0   9000 2021-08-15  人事部
6  老王  28.0   0.0   8500 2018-03-10  技术部
8  赵六  28.0  10.0  16000 2019-12-01  财务部

数据类型：
 姓名              object
年龄             float64
工龄             float64
薪资               int64
入职日期    datetime64[ns]
部门              object
dtype: object

/var/folders/0g/nrnvk53s0plcwpw5_0_4jn_40000gn/T/ipykernel_26345/2796107049.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['年龄'].fillna(df['年龄'].median(), inplace=True)
/var/folders/0g/nrnvk53s0plcwpw5_0_4jn_40000gn/T/ipykernel_26345/2796107049.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['工龄'].fillna(df['工龄'].median(), inplace=True)

In [12]:
import pandas as pd
import numpy as np

# 模拟生成数据（注意：这里故意加了缺失值、异常值、重复数据以及格式混乱的日期）
data = {
    "姓名": ["张三", "李四", "王五", "赵六", "小明", "小红", "老王", "张三", "赵六"],
    "年龄": [25, 30, 22, np.nan, 29, 26, 28, 25, 200],  # 缺失值 & 异常值
    "工龄": [2, 5, 1, 8, np.nan, 3, -1, 2, 10],          # 缺失值 & 错误数据（负数）
    "薪资": [8000, 12000, 6000, 15000, 10000, 9000, 8500, 8000, 16000],  # 重复行
    "入职日期": ["2022-06-01", "2020/05/15", "2021-09-10", "2019-12-01", 
               "2023/01/01", "2021-08-15", "2018-03-10", "2022-06-01", "2019-12-01"],  # 日期格式混乱
    "部门": ["市场部", "技术部", "市场部", "技术部", "市场部", "人事部", "技术部", "市场部", "财务部"]
}

df = pd.DataFrame(data)
print("导入数据：\n", df)

导入数据：
    姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
7  张三   25.0   2.0   8000  2022-06-01  市场部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

In [13]:
import pandas as pd
import numpy as np

In [14]:
# 模拟生成数据（注意：这里故意加了缺失值、异常值、重复数据以及格式混乱的日期）
data = {
    "姓名": ["张三", "李四", "王五", "赵六", "小明", "小红", "老王", "张三", "赵六"],
    "年龄": [25, 30, 22, np.nan, 29, 26, 28, 25, 200],  # 缺失值 & 异常值
    "工龄": [2, 5, 1, 8, np.nan, 3, -1, 2, 10],        # 缺失值 & 错误数据（负数）
    "薪资": [8000, 12000, 6000, 15000, 10000, 9000, 8500, 8000, 16000], # 重复行
    "入职日期": ["2022-06-01", "2020/05/15", "2021-09-10", "2019-12-01", "2023/01/01", "2021-08-15", "2018-03-10", "2022-06-01", "2019-12-01"],# 重复行
    "部门": ["市场部", "技术部", "市场部", "技术部", "市场部", "人事部", "技术部", "市场部", "财务部"]
}

df = pd.DataFrame(data)

In [15]:
# 模拟生成数据（注意：这里故意加了缺失值、异常值、重复数据以及格式混乱的日期）, 来源于网上
data = {
       "姓名":["张三","李四","王五","赵六","小明","小红","老王","张三","赵六"], 
       "年龄":[25,30,22,np.nan,29,26,28,25,200],                         # 缺失值 & 异常值
    "工龄":[2,5,1,8,np.nan,3,-1,2,10],                     # 缺失值 & 错误数据（负数）
    "薪资":[8000,12000,6000,15000,10000,9000,8500,8000,16000],  # 重复行
    "入职日期":["2022-06-01","2020/05/15","2021-09-10","2019-12-01","2023/01/01","2021-08-15","2018-03-10","2022-06-01","2019-12-01"],  # 重复行
    "部门":["市场部","技术部","市场部","技术部","市场部","人事部","技术部","市场部","财务部"]
       }

SyntaxError: invalid non-printable character U+00A0 (2217484780.py, line 3)

In [ ]:
print("导入数据：\n", df)

导入数据：
    姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
7  张三   25.0   2.0   8000  2022-06-01  市场部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

## 数据保存与读取

### 保存CSV,xls文件

In [ ]:
df

   姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
7  张三   25.0   2.0   8000  2022-06-01  市场部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

In [ ]:
df.to_csv('23089056孙琉屿1.csv',index=True)

In [ ]:
df.to_csv('23089056孙琉屿.csv')

In [ ]:
df.to_excel('23089056孙琉屿.xlsx')

### 读取CSV文件

In [ ]:
# 读取CSV文件（确保data.csv文件在当前目录下）
df_csv = pd.read_csv('data.csv')
print("CSV数据预览：")
print(df_csv.head())

CSV数据预览：
   Unnamed: 0  姓名    年龄   工龄     薪资        入职日期   部门
0           0  张三  25.0  2.0   8000  2022-06-01  市场部
1           1  李四  30.0  5.0  12000  2020/05/15  技术部
2           2  王五  22.0  1.0   6000  2021-09-10  市场部
3           3  赵六   NaN  8.0  15000  2019-12-01  技术部
4           4  小明  29.0  NaN  10000  2023/01/01  市场部

In [ ]:
df_csv

   Unnamed: 0  姓名     年龄    工龄     薪资        入职日期   部门
0           0  张三   25.0   2.0   8000  2022-06-01  市场部
1           1  李四   30.0   5.0  12000  2020/05/15  技术部
2           2  王五   22.0   1.0   6000  2021-09-10  市场部
3           3  赵六    NaN   8.0  15000  2019-12-01  技术部
4           4  小明   29.0   NaN  10000  2023/01/01  市场部
5           5  小红   26.0   3.0   9000  2021-08-15  人事部
6           6  老王   28.0  -1.0   8500  2018-03-10  技术部
7           7  张三   25.0   2.0   8000  2022-06-01  市场部
8           8  赵六  200.0  10.0  16000  2019-12-01  财务部

In [ ]:
# 读取Excel文件的第一个工作表
df_excel = pd.read_excel('23089056孙琉屿.xlsx', sheet_name='Sheet1')
print("Excel数据预览：")
print(df_excel.head())
df_excel

Excel数据预览：
   Unnamed: 0  姓名    年龄   工龄     薪资        入职日期   部门
0           0  张三  25.0  2.0   8000  2022-06-01  市场部
1           1  李四  30.0  5.0  12000  2020/05/15  技术部
2           2  王五  22.0  1.0   6000  2021-09-10  市场部
3           3  赵六   NaN  8.0  15000  2019-12-01  技术部
4           4  小明  29.0  NaN  10000  2023/01/01  市场部

   Unnamed: 0  姓名     年龄    工龄     薪资        入职日期   部门
0           0  张三   25.0   2.0   8000  2022-06-01  市场部
1           1  李四   30.0   5.0  12000  2020/05/15  技术部
2           2  王五   22.0   1.0   6000  2021-09-10  市场部
3           3  赵六    NaN   8.0  15000  2019-12-01  技术部
4           4  小明   29.0   NaN  10000  2023/01/01  市场部
5           5  小红   26.0   3.0   9000  2021-08-15  人事部
6           6  老王   28.0  -1.0   8500  2018-03-10  技术部
7           7  张三   25.0   2.0   8000  2022-06-01  市场部
8           8  赵六  200.0  10.0  16000  2019-12-01  财务部

说明：pd.read_excel() 可以指定工作表名（或索引）。  

#stocks.to_csv('stocks.csv',index=True)
#stocks1 =pd.read_csv('stocks.csv',index_col = 'trade_date')   #考点

## 数据清洗
数据清洗其实就是对症下药，让数据变得干净、标准，便于后续处理。这里主要包括：

### 缺失值处理
首先看看哪些地方数据“不完整”：

In [ ]:
print("缺失值统计：\n", df.isnull().sum())

缺失值统计：
 姓名      0
年龄      1
工龄      1
薪资      0
入职日期    0
部门      0
dtype: int64

通过缺失值统计可以发现年龄和工龄2列分别有1个缺失值。

处理策略：

.年龄 缺失值用中位数填充（受极端值影响小）

.工龄 缺失值用部门内均值补全（让每个部门的数据更有说服力）

In [ ]:
df["年龄"]=df["年龄"].fillna(df["年龄"].median())
df["工龄"]=df["工龄"].fillna(df.groupby("部门")["工龄"].transform("mean"))

In [ ]:
df

   姓名     年龄         工龄     薪资        入职日期   部门
0  张三   25.0   2.000000   8000  2022-06-01  市场部
1  李四   30.0   5.000000  12000  2020/05/15  技术部
2  王五   22.0   1.000000   6000  2021-09-10  市场部
3  赵六   27.0   8.000000  15000  2019-12-01  技术部
4  小明   29.0   1.666667  10000  2023/01/01  市场部
5  小红   26.0   3.000000   9000  2021-08-15  人事部
6  老王   28.0  -1.000000   8500  2018-03-10  技术部
7  张三   25.0   2.000000   8000  2022-06-01  市场部
8  赵六  200.0  10.000000  16000  2019-12-01  财务部

### 删除缺失值与填充

适用于：

缺失值占比极少（比如 < 5%）

该列不是关键数据业务

可以接受少量数据丢失

In [ ]:
import pandas as pd

# 创建数据框
df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五', None, '赵六'],
    '年龄': [23, 25, None, 30, 28],
    '薪资': [5000, 7000, None, 8000, 9000]
})

# 删除含缺失值的行
df_dropna = df.dropna()

# 打印结果
print(df_dropna)

   姓名    年龄      薪资
0  张三  23.0  5000.0
1  李四  25.0  7000.0
4  赵六  28.0  9000.0

In [ ]:
# 使用 fillna 填充缺失值
df_filled = df.fillna({
    '姓名': '未知',
    '年龄': df['年龄'].mean(),  # 使用年龄列的平均值填充
    '薪资': 0  # 使用 0 填充薪资列的缺失值
})

# 打印结果
print(df_filled)

   姓名    年龄      薪资
0  张三  23.0  5000.0
1  李四  25.0  7000.0
2  王五  26.5     0.0
3  未知  30.0  8000.0
4  赵六  28.0  9000.0

df.fillna(value) 可用于填充缺失值

df['某列'].mean()  用该列均值填充（适用于数值数据）

df['某列'].median()  用中位数填充，适用于受极端值影响的数据

df['某列'].mode()[0]  用众数填充（适用于分类变量）

In [ ]:
df_interpolated = df.interpolate()
print(df_interpolated)

     姓名    年龄      薪资
0    张三  23.0  5000.0
1    李四  25.0  7000.0
2    王五  27.5  7500.0
3  None  30.0  8000.0
4    赵六  28.0  9000.0

/var/folders/0g/nrnvk53s0plcwpw5_0_4jn_40000gn/T/ipykernel_99863/876667172.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()

interpolate() 采用线性插值法填充数值缺失值（适用于趋势平稳的数据）

In [ ]:
# 前向填充（用前一行数据填充）
df_ffill = df.ffill()

# 后向填充（用后一行数据填充）
df_bfill = df.bfill()

# 打印结果
print("前向填充结果：")
print(df_ffill)
print("\n后向填充结果：")
print(df_bfill)

前向填充结果：
   姓名    年龄      薪资
0  张三  23.0  5000.0
1  李四  25.0  7000.0
2  王五  25.0  7000.0
3  王五  30.0  8000.0
4  赵六  28.0  9000.0

后向填充结果：
   姓名    年龄      薪资
0  张三  23.0  5000.0
1  李四  25.0  7000.0
2  王五  30.0  8000.0
3  赵六  30.0  8000.0
4  赵六  28.0  9000.0

### 机器学习模型预测填充

In [ ]:
# 创建数据框
df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五', None, '赵六'],
    '年龄': [23, 25, None, 30, 28],
    '薪资': [5000, 7000, None, 8000, 9000]
})

In [ ]:
df

     姓名    年龄      薪资
0    张三  23.0  5000.0
1    李四  25.0  7000.0
2    王五   NaN     NaN
3  None  30.0  8000.0
4    赵六  28.0  9000.0

In [ ]:
# 使用 SimpleImputer 填充缺失值
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')  # 也可以换成 'median' 或 'most_frequent'

# 只对 '年龄' 列进行填充
df['年龄'] = imputer.fit_transform(df[['年龄']])

# 打印结果
print(df)

     姓名    年龄      薪资
0    张三  23.0  5000.0
1    李四  25.0  7000.0
2    王五  26.5     NaN
3  None  30.0  8000.0
4    赵六  28.0  9000.0

### 剔除异常值

In [ ]:
import pandas as pd

# 创建数据框
df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五', '赵六', '小明', '小红', '老王', '张三', '赵六'],
    '年龄': [25, 30, 22, None, 29, 26, 28, 25, 200],  # 缺失值 & 异常值
    '工龄': [2, 5, 1, 8, None, 3, -1, 2, 10],        # 缺失值 & 错误数据（负数）
    '薪资': [8000, 12000, 6000, 15000, 10000, 9000, 8500, 8000, 16000],  # 重复行
    '入职日期': ["2022-06-01", "2020/05/15", "2021-09-10", "2019-12-01", "2023/01/01", "2021-08-15", "2018-03-10", "2022-06-01", "2019-12-01"],  # 日期格式混乱
    '部门': ["市场部", "技术部", "市场部", "技术部", "市场部", "人事部", "技术部", "市场部", "财务部"]
})
df

   姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
7  张三   25.0   2.0   8000  2022-06-01  市场部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

In [ ]:

# 处理年龄异常值：用箱线图法（IQR）检测并剔除异常值
Q1 = df["年龄"].quantile(0.25)
Q3 = df["年龄"].quantile(0.75)
IQR = Q3 - Q1
df = df[(df["年龄"] >= Q1 - 1.5 * IQR) & (df["年龄"] <= Q3 + 1.5 * IQR)]

# 工龄负数也不合理，直接过滤
df = df[df["工龄"] >= 0]

df

   姓名    年龄   工龄     薪资        入职日期   部门
0  张三  25.0  2.0   8000  2022-06-01  市场部
1  李四  30.0  5.0  12000  2020/05/15  技术部
2  王五  22.0  1.0   6000  2021-09-10  市场部
5  小红  26.0  3.0   9000  2021-08-15  人事部
7  张三  25.0  2.0   8000  2022-06-01  市场部

In [ ]:
# 创建数据框
df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五', '赵六', '小明', '小红', '老王', '张三', '赵六'],
    '年龄': [25, 30, 22, None, 29, 26, 28, 25, 200],  # 缺失值 & 异常值
    '工龄': [2, 5, 1, 8, None, 3, -1, 2, 10],        # 缺失值 & 错误数据（负数）
    '薪资': [8000, 12000, 6000, 15000, 10000, 9000, 8500, 8000, 16000],  # 重复行
    '入职日期': ["2022-06-01", "2020/05/15", "2021-09-10", "2019-12-01", "2023/01/01", "2021-08-15", "2018-03-10", "2022-06-01", "2019-12-01"],  # 日期格式混乱
    '部门': ["市场部", "技术部", "市场部", "技术部", "市场部", "人事部", "技术部", "市场部", "财务部"]
})
df

   姓名     年龄    工龄     薪资        入职日期   部门
0  张三   25.0   2.0   8000  2022-06-01  市场部
1  李四   30.0   5.0  12000  2020/05/15  技术部
2  王五   22.0   1.0   6000  2021-09-10  市场部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
4  小明   29.0   NaN  10000  2023/01/01  市场部
5  小红   26.0   3.0   9000  2021-08-15  人事部
6  老王   28.0  -1.0   8500  2018-03-10  技术部
7  张三   25.0   2.0   8000  2022-06-01  市场部
8  赵六  200.0  10.0  16000  2019-12-01  财务部

In [ ]:
df_filtered = df[df['薪资'] > 10000]  # 只保留薪资大于10000的数据
df_filtered

   姓名     年龄    工龄     薪资        入职日期   部门
1  李四   30.0   5.0  12000  2020/05/15  技术部
3  赵六    NaN   8.0  15000  2019-12-01  技术部
8  赵六  200.0  10.0  16000  2019-12-01  财务部